/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day07custdialogfriends;

import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Day07CustDialogFriends extends javax.swing.JFrame {

    
    DefaultListModel <String> modelFriendsList = new DefaultListModel<>();
    /**
     * Creates new form Day07CustDialogFriends
     */
    public Day07CustDialogFriends() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAddEdit = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        dlgAddEdit_tfName = new javax.swing.JTextField();
        dlgAddEdit_btCancel = new javax.swing.JButton();
        dlgAddEdit_btSave = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFriends = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAddFriend = new javax.swing.JMenu();

        dlgAddEdit.setModal(true);

        jLabel1.setText("Name:");

        dlgAddEdit_btCancel.setText("Cancel");
        dlgAddEdit_btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgAddEdit_btCancelActionPerformed(evt);
            }
        });

        dlgAddEdit_btSave.setText("Save");
        dlgAddEdit_btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgAddEdit_btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgAddEditLayout = new javax.swing.GroupLayout(dlgAddEdit.getContentPane());
        dlgAddEdit.getContentPane().setLayout(dlgAddEditLayout);
        dlgAddEditLayout.setHorizontalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddEditLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(dlgAddEdit_btCancel)
                        .addGap(28, 28, 28)
                        .addComponent(dlgAddEdit_btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddEditLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dlgAddEdit_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        dlgAddEditLayout.setVerticalGroup(
            dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddEditLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dlgAddEdit_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgAddEdit_btCancel)
                    .addComponent(dlgAddEdit_btSave))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStatus.setText("jLabel1");
        lblStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblStatus, java.awt.BorderLayout.PAGE_END);

        lstFriends.setModel(modelFriendsList);
        lstFriends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFriendsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstFriends);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        miAddFriend.setText("Add friend");
        miAddFriend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miAddFriendMouseClicked(evt);
            }
        });
        miAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddFriendActionPerformed(evt);
            }
        });
        jMenuBar1.add(miAddFriend);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void miAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddFriendActionPerformed
   
       
    }//GEN-LAST:event_miAddFriendActionPerformed

    //when "Add friend" clicked this method will be called (use "Add frind" as a button)
    //dialog window will become visible only when all this method will finish
    private void miAddFriendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miAddFriendMouseClicked
        dlgAddEdit_btSave.setText("Add friend");       
        
        //get values of selected item to text filed
        currentlyEditedItemIndex = -1;
        
        //cleanup the dialog before showing it
        dlgAddEdit_tfName.setText("");
        //to resize window to fit components
        dlgAddEdit.pack();
        //set location relative to parent, so dialog shows in the center of parent(JFrame)
        dlgAddEdit.setLocationRelativeTo(this);
        //set dialog visible
        dlgAddEdit.setVisible(true);
    }//GEN-LAST:event_miAddFriendMouseClicked

    private void dlgAddEdit_btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgAddEdit_btCancelActionPerformed
      //when "Cancel" button is pressed to make dialog not visible
      dlgAddEdit.setVisible(false);
    }//GEN-LAST:event_dlgAddEdit_btCancelActionPerformed

    private void dlgAddEdit_btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgAddEdit_btSaveActionPerformed
        String name = dlgAddEdit_tfName.getText();
        //make sure name is not empty
        if(name.length() == 0)
        {
             JOptionPane.showMessageDialog(this,"Name cannot be empty",
                    "Input error",  
                       JOptionPane.ERROR_MESSAGE);
             return;
        }
        if(currentlyEditedItemIndex == -1)
        {
            //add name to model
            modelFriendsList.addElement(name);
        }
        else
        {
            modelFriendsList.set(currentlyEditedItemIndex, name);
        }
        
        //hide dialog window
        dlgAddEdit.setVisible(false);
    }//GEN-LAST:event_dlgAddEdit_btSaveActionPerformed

    //creating varuable that will help to indicated in we are adding item or editing
    int currentlyEditedItemIndex = -1;   //adding, not editing
 
    
    
    //when we clicked mouse and choose an item this method will happen
    private void lstFriendsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFriendsMouseClicked
       //to check if mouse was clicked 2 times and only right button was clicked
        if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1)
       {
           int index = lstFriends.getSelectedIndex();
           if(index == -1)
           {
               return; //no selection
           }
            dlgAddEdit_btSave.setText("Update friend");
           
           
            currentlyEditedItemIndex = index;
            
            //cleanup the dialog before showing it
            dlgAddEdit_tfName.setText(modelFriendsList.get(index));
            
            //to resize window to fit components
            dlgAddEdit.pack();
            //set location relative to parent, so dialog shows in the center of parent(JFrame)
            dlgAddEdit.setLocationRelativeTo(this);
            //set dialog visible
            dlgAddEdit.setVisible(true);
       }
    }//GEN-LAST:event_lstFriendsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day07CustDialogFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day07CustDialogFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day07CustDialogFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day07CustDialogFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day07CustDialogFriends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgAddEdit;
    private javax.swing.JButton dlgAddEdit_btCancel;
    private javax.swing.JButton dlgAddEdit_btSave;
    private javax.swing.JTextField dlgAddEdit_tfName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<String> lstFriends;
    private javax.swing.JMenu miAddFriend;
    // End of variables declaration//GEN-END:variables
}
